### ISSUE TITLE
Failed to upload images

### ISSUE THREAD

**Issue by johnreytanquinco** [goalgorilla/open_social_docker#2]
We have successfully installed in OpenShift server the Open Social docker image(latest) provided here.
[docker image](https://hub.docker.com/r/goalgorilla/open_social_docker/tags/)

Now when I am trying to create any content with "image "as field, uploading any photo is displaying a failing result.

## **ERROR output on page**
```
The file could not be saved. An unknown error has occurred.
File upload error. Could not move uploaded file.
```

## **Checking the logs in the server:**
`"POST /node/add/finfeed1?element_parents=field_image/widget/0&ajax_form=1&_wrapper_format=drupal_ajax HTTP/1.1" 200 6434`

## **Additional details**
- We have allocated 1GiB size for its mysql container.

Checking the Media File system config:
Public file system path = "sites/default/files"
Temporary directory = "sites/default/files/temp"

Reading this note about the Temporary directory "A local file system path where temporary files will be stored. This directory should not be accessible over the web.". Since its path is located inside Drupal, I am assuming that this causes the error.

I change the permission of folders sites/default/files/temp to 777.

**Comment by johnreytanquinco** [comment]
UPDATE:

I have a volume mount to my database, I think I need to create another volume for Drupal files, is that so?

**Comment by ronaldtebrake** [comment]
For any issues with the platform we kindly ask you to use the [drupal.org](http://www.drupal.org/project/issues/social) issue queue. This way we can centralise all the information and make the feedback available for other users for documentation purposes. Next to giving people the credit they deserve.
